spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.opspilot: ${LOGGING_LEVEL_COM_OPSPILOT:INFO}
